project_id = "vlvqevzienyrlwlproxpj"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
external_email_enabled = true
external_phone_enabled = true
external_apple_enabled = false
external_azure_enabled = false
external_bitbucket_enabled = false
external_discord_enabled = false
external_facebook_enabled = false
external_github_enabled = false
external_gitlab_enabled = false
external_google_enabled = false
external_keycloak_enabled = false
external_linkedin_enabled = false
external_notion_enabled = false
external_slack_enabled = false
external_spotify_enabled = false
external_twitch_enabled = false
external_twitter_enabled = false
external_workos_enabled = false
external_zoom_enabled = false

[functions.generate-scheduled-content]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.generate-rss]
verify_jwt = false

[edge-runtime]
enabled = true
inspector_port = 8083