// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlvqevzienylwlproxpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsdnFldnppZW55bHdscHJveHBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1OTE2MDksImV4cCI6MjA2MzE2NzYwOX0.Ye9W2uo49nwt1EUtqFAH3uwhFjJc2VcaAs_le9mMNXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);